"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { api, type PackDetail, type PackDocumentOut } from "@/lib/api";

const KIND_LABEL: Record<string, string> = {
  landlord_memo: "Landlord memo",
  comparables_schedule: "Comparables schedule",
  itza_analysis: "ITZA / £/sq ft analysis",
  trigger_letter: "Trigger letter",
};

export default function PackDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [pack, setPack] = useState<PackDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeKind, setActiveKind] = useState<string | null>(null);

  const load = () => api.getPack(id).then(setPack).catch((e) => setError(String(e)));

  useEffect(() => {
    void load();
    const interval = setInterval(() => {
      setPack((prev) => {
        if (prev && prev.status === "generating") void load();
        return prev;
      });
    }, 3000);
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  useEffect(() => {
    if (pack && pack.documents.length > 0 && activeKind === null) {
      setActiveKind(pack.documents[0].kind);
    }
  }, [pack, activeKind]);

  if (error) return <div className="p-8 text-sm text-red-700">{error}</div>;
  if (!pack) return <div className="p-8 text-sm text-neutral-500">Loading…</div>;

  const activeDoc = pack.documents.find((d) => d.kind === activeKind);

  return (
    <div className="mx-auto max-w-6xl px-6 py-6">
      <Link href="/packs" className="text-xs text-neutral-500 hover:text-neutral-700">← All packs</Link>
      <div className="mt-1 mb-5">
        <h1 className="text-xl font-semibold">{pack.lease_label ?? pack.lease_id}</h1>
        <div className="text-xs text-neutral-500 mt-1">
          {pack.generator_model && <>Generated by {pack.generator_model} in {pack.generated_seconds?.toFixed(1)}s</>}
          {pack.comparables_used_count > 0 && <> · {pack.comparables_used_count} comparable{pack.comparables_used_count === 1 ? "" : "s"}</>}
          <> · created {format(parseISO(pack.created_at), "d MMM yyyy HH:mm")}</>
        </div>
      </div>

      {pack.status === "generating" && (
        <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          Generating pack… this typically takes 30–90 seconds.
        </div>
      )}

      {pack.status === "failed" && (
        <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800 whitespace-pre-wrap">
          <div className="font-medium mb-1">Pack generation failed</div>
          {pack.error}
        </div>
      )}

      {pack.status !== "generating" && pack.status !== "failed" && (
        <>
          <HeadlineNumbers pack={pack} onChanged={load} />
          {pack.documents.length > 0 && (
            <div className="mt-6 grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6">
              <nav className="space-y-1">
                {pack.documents.map((d) => (
                  <button
                    key={d.id}
                    onClick={() => setActiveKind(d.kind)}
                    className={`w-full text-left rounded-md px-3 py-2 text-sm ${
                      activeKind === d.kind
                        ? "bg-neutral-900 text-white"
                        : "bg-white border border-neutral-200 hover:bg-neutral-50"
                    }`}
                  >
                    {KIND_LABEL[d.kind] ?? d.kind}
                  </button>
                ))}
              </nav>
              {activeDoc ? <DocumentView packId={pack.id} doc={activeDoc} /> : null}
            </div>
          )}
        </>
      )}
    </div>
  );
}

function HeadlineNumbers({ pack, onChanged }: { pack: PackDetail; onChanged: () => Promise<void> }) {
  return (
    <div className="rounded-lg border border-neutral-200 bg-white p-5">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <NumberCell label="Current rent" value={pack.current_rent_gbp} />
        <NumberCell label="Recommended opening" value={pack.recommended_opening_gbp} highlight />
        <NumberCell label="Settlement range" value={pack.recommended_settlement_low_gbp} suffix={pack.recommended_settlement_high_gbp ? ` – £${pack.recommended_settlement_high_gbp.toLocaleString()}` : ""} />
        <NumberCell label={pack.status === "settled" ? "Settled" : "—"} value={pack.settled_rent_gbp} />
      </div>
      <div className="mt-5 flex flex-wrap gap-2">
        <button
          disabled={pack.status === "settled" || pack.status === "sent"}
          onClick={async () => {
            await api.markPackSent(pack.id);
            await onChanged();
          }}
          className="rounded-md border border-neutral-300 bg-white px-3 py-1.5 text-sm hover:bg-neutral-50 disabled:opacity-50"
        >
          {pack.status === "sent" ? "Marked as sent" : "Mark as sent"}
        </button>
        <SettleButton pack={pack} onChanged={onChanged} />
      </div>
    </div>
  );
}

function NumberCell({ label, value, suffix = "", highlight = false }: { label: string; value: number | null; suffix?: string; highlight?: boolean }) {
  return (
    <div>
      <div className="text-xs uppercase tracking-wide text-neutral-500">{label}</div>
      <div className={`mt-1 ${highlight ? "text-2xl font-semibold text-neutral-900" : "text-xl font-medium text-neutral-900"}`}>
        {value == null ? "—" : `£${value.toLocaleString()}${suffix}`}
      </div>
    </div>
  );
}

function SettleButton({ pack, onChanged }: { pack: PackDetail; onChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return (
    <button
      disabled={busy || pack.status === "settled"}
      onClick={async () => {
        const raw = window.prompt(
          "Record settled rent (£/year):",
          pack.recommended_settlement_low_gbp ? String(pack.recommended_settlement_low_gbp) : ""
        );
        if (!raw) return;
        const num = parseFloat(raw.replace(/[, £]/g, ""));
        if (Number.isNaN(num)) return alert("Enter a number.");
        setBusy(true);
        try {
          await api.settlePack(pack.id, num);
          await onChanged();
        } finally {
          setBusy(false);
        }
      }}
      className="rounded-md bg-emerald-600 px-3 py-1.5 text-sm text-white hover:bg-emerald-700 disabled:opacity-50"
    >
      {pack.status === "settled" ? "Settled" : busy ? "Saving…" : "Record settlement"}
    </button>
  );
}

function DocumentView({ packId, doc }: { packId: string; doc: PackDocumentOut }) {
  return (
    <div className="rounded-lg border border-neutral-200 bg-white">
      <div className="flex items-center justify-between border-b border-neutral-200 px-4 py-2.5">
        <div className="text-sm font-medium">{KIND_LABEL[doc.kind] ?? doc.kind}</div>
        <a
          href={api.packDocumentUrl(packId, doc.id)}
          className="rounded-md bg-neutral-900 px-3 py-1.5 text-xs text-white hover:bg-neutral-700"
          download={doc.filename}
        >
          Download .docx
        </a>
      </div>
      <div className="prose prose-sm max-w-none p-5 prose-headings:mt-3 prose-headings:mb-1 prose-p:my-2 prose-table:my-2 prose-th:bg-neutral-50">
        {doc.markdown_content ? (
          <Markdown text={doc.markdown_content} />
        ) : (
          <div className="text-neutral-500 text-sm italic">No preview available.</div>
        )}
      </div>
    </div>
  );
}

function Markdown({ text }: { text: string }) {
  // Lightweight markdown renderer — handles headings, bold, bullets, tables, paragraphs.
  // Avoids pulling in a full markdown library.
  const blocks = parseBlocks(text);
  return (
    <>
      {blocks.map((b, i) => {
        if (b.type === "heading") {
          const Tag = (`h${b.level}` as unknown) as keyof React.JSX.IntrinsicElements;
          return <Tag key={i}>{renderInline(b.text)}</Tag>;
        }
        if (b.type === "bullets") {
          return (
            <ul key={i}>
              {b.items.map((item, j) => <li key={j}>{renderInline(item)}</li>)}
            </ul>
          );
        }
        if (b.type === "numbered") {
          return (
            <ol key={i}>
              {b.items.map((item, j) => <li key={j}>{renderInline(item)}</li>)}
            </ol>
          );
        }
        if (b.type === "table") {
          return (
            <table key={i} className="text-xs">
              <thead>
                <tr>{b.header.map((h, j) => <th key={j}>{renderInline(h)}</th>)}</tr>
              </thead>
              <tbody>
                {b.rows.map((row, ri) => (
                  <tr key={ri}>{row.map((c, ci) => <td key={ci}>{renderInline(c)}</td>)}</tr>
                ))}
              </tbody>
            </table>
          );
        }
        return <p key={i}>{renderInline(b.text)}</p>;
      })}
    </>
  );
}

type Block =
  | { type: "heading"; level: 1 | 2 | 3; text: string }
  | { type: "paragraph"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "numbered"; items: string[] }
  | { type: "table"; header: string[]; rows: string[][] };

function parseBlocks(md: string): Block[] {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const blocks: Block[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }

    if (line.startsWith("### ")) { blocks.push({ type: "heading", level: 3, text: line.slice(4) }); i++; continue; }
    if (line.startsWith("## "))  { blocks.push({ type: "heading", level: 2, text: line.slice(3) }); i++; continue; }
    if (line.startsWith("# "))   { blocks.push({ type: "heading", level: 1, text: line.slice(2) }); i++; continue; }

    if (line.trimStart().startsWith("|") && i + 1 < lines.length && lines[i + 1].includes("---")) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trimStart().startsWith("|")) { tableLines.push(lines[i]); i++; }
      const cells = (l: string) => l.trim().replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
      const header = cells(tableLines[0]);
      const rows = tableLines.slice(2).map(cells);
      blocks.push({ type: "table", header, rows });
      continue;
    }

    if (/^[-*] /.test(line.trimStart())) {
      const items: string[] = [];
      while (i < lines.length && /^[-*] /.test(lines[i].trimStart())) {
        items.push(lines[i].trimStart().replace(/^[-*] /, ""));
        i++;
      }
      blocks.push({ type: "bullets", items });
      continue;
    }

    if (/^\d+\.\s/.test(line.trimStart())) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\.\s/.test(lines[i].trimStart())) {
        items.push(lines[i].trimStart().replace(/^\d+\.\s/, ""));
        i++;
      }
      blocks.push({ type: "numbered", items });
      continue;
    }

    const paraLines = [line];
    i++;
    while (i < lines.length && lines[i].trim() && !/^([#\-*|]|\d+\.\s)/.test(lines[i].trimStart())) {
      paraLines.push(lines[i]);
      i++;
    }
    blocks.push({ type: "paragraph", text: paraLines.join(" ") });
  }
  return blocks;
}

function renderInline(text: string): React.ReactNode {
  // Bold via **...**
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith("**") && p.endsWith("**") ? <strong key={i}>{p.slice(2, -2)}</strong> : <span key={i}>{p}</span>
      )}
    </>
  );
}
