"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import {
  Briefcase,
  Check,
  ExternalLink,
  FileText,
  Pencil,
  Send,
  X,
} from "lucide-react";
import { api, type Comparable, type PackDetail, type PackDocumentOut } from "@/lib/api";
import { useApi } from "@/lib/use-api";
import { StatusPill } from "@/components/ui/status-pill";
import { ErrorState } from "@/components/ui/error-state";

const KIND_LABEL: Record<string, string> = {
  landlord_memo: "Landlord memo",
  comparables_schedule: "Comparables schedule",
  itza_analysis: "ITZA / £/sq ft analysis",
  trigger_letter: "Trigger letter",
};

const KIND_ICON: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  landlord_memo: FileText,
  comparables_schedule: Briefcase,
  itza_analysis: FileText,
  trigger_letter: Send,
};

const KIND_ORDER = ["landlord_memo", "comparables_schedule", "itza_analysis", "trigger_letter"];

export default function PackDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const packQ = useApi<PackDetail>((opts) => api.getPack(id, opts), [id]);
  const pack = packQ.data;
  const error = packQ.error;
  const load = packQ.refetch;
  const [activeKind, setActiveKind] = useState<string | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);

  // Poll while generating
  useEffect(() => {
    if (pack?.status !== "generating") return;
    const interval = setInterval(() => packQ.refetch(), 3000);
    return () => clearInterval(interval);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pack?.status]);

  useEffect(() => {
    if (pack && pack.documents.length > 0 && activeKind === null) {
      // Force the canonical order regardless of insertion order
      const sorted = KIND_ORDER.find((k) => pack.documents.some((d) => d.kind === k));
      setActiveKind(sorted ?? pack.documents[0].kind);
    }
  }, [pack, activeKind]);

  if (error && !pack) {
    return (
      <div className="p-8 max-w-xl mx-auto">
        <ErrorState error={error} onRetry={load} retrying={packQ.refetching} />
      </div>
    );
  }
  if (!pack) return <div className="p-8 text-sm text-neutral-500">Loading…</div>;

  const sortedDocs = [...pack.documents].sort(
    (a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind)
  );
  const activeDoc = sortedDocs.find((d) => d.kind === activeKind);

  return (
    <div className="mx-auto max-w-6xl px-6 py-6">
      {/* Breadcrumbs + title */}
      <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 text-xs text-neutral-500 mb-1">
        <Link href="/today" className="hover:text-neutral-800">Home</Link>
        <span aria-hidden>›</span>
        <Link href="/packs" className="hover:text-neutral-800">Review packs</Link>
        <span aria-hidden>›</span>
        <Link href={`/leases/${pack.lease_id}`} className="hover:text-neutral-800 truncate max-w-[28ch]">
          {pack.lease_label ?? "Lease"}
        </Link>
        <span aria-hidden>›</span>
        <span className="text-neutral-800">Pack</span>
      </nav>
      <header className="mb-5 flex items-start justify-between gap-4">
        <div className="min-w-0">
          <h1 className="text-xl font-semibold truncate" title={pack.lease_label ?? ""}>
            {pack.lease_label ?? pack.lease_id}
          </h1>
          <div className="mt-1 flex items-center gap-2 text-xs text-neutral-500">
            <StatusPill group="pack_status" value={pack.status} />
            {pack.generator_model && (
              <span>· Generated by {pack.generator_model} in {pack.generated_seconds?.toFixed(1)}s</span>
            )}
            <span>· created {format(parseISO(pack.created_at), "d MMM yyyy HH:mm")}</span>
          </div>
        </div>
      </header>

      {pack.status === "generating" && (
        <div className="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          Generating pack… this typically takes 30–90 seconds.
        </div>
      )}

      {pack.status === "failed" && (
        <div className="mb-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800 whitespace-pre-wrap">
          <div className="font-medium mb-1">Pack generation failed</div>
          {pack.error}
        </div>
      )}

      {pack.status !== "generating" && pack.status !== "failed" && (
        <>
          {/* Headline numbers — inline editable */}
          <HeadlineNumbers pack={pack} onChanged={async () => { load(); }} />

          {/* Doc viewer with sidebar nav */}
          {sortedDocs.length > 0 && (
            <div className="mt-6 grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6">
              <nav className="space-y-1">
                {sortedDocs.map((d) => {
                  const Icon = KIND_ICON[d.kind] ?? FileText;
                  return (
                    <button
                      key={d.id}
                      onClick={() => setActiveKind(d.kind)}
                      className={`w-full flex items-center gap-2 rounded-md px-3 py-2 text-left text-sm ${
                        activeKind === d.kind
                          ? "bg-neutral-900 text-white"
                          : "bg-white border border-neutral-200 hover:bg-neutral-50"
                      }`}
                    >
                      <Icon size={14} className={activeKind === d.kind ? "text-white" : "text-neutral-500"} />
                      <span className="flex-1 truncate">{KIND_LABEL[d.kind] ?? d.kind}</span>
                    </button>
                  );
                })}
                <button
                  onClick={() => setDrawerOpen(true)}
                  className="mt-3 w-full rounded-md border border-neutral-200 bg-white px-3 py-2 text-left text-xs text-neutral-600 hover:bg-neutral-50"
                >
                  📊 {pack.comparables_used_count ?? 0} comparable{(pack.comparables_used_count ?? 0) === 1 ? "" : "s"} used →
                </button>
              </nav>
              {activeDoc && <DocumentView packId={pack.id} doc={activeDoc} />}
            </div>
          )}
        </>
      )}

      <ComparablesDrawer open={drawerOpen} onClose={() => setDrawerOpen(false)} />
    </div>
  );
}

// ---- headline numbers (inline editable) --------------------------------

function HeadlineNumbers({ pack, onChanged }: { pack: PackDetail; onChanged: () => Promise<void> }) {
  const editable = pack.status === "draft" || pack.status === "sent";

  return (
    <div className="rounded-lg border border-neutral-200 bg-white p-5">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <NumberCell label="Current rent" value={pack.current_rent_gbp} editable={false} />
        <NumberCell
          label="Recommended opening"
          value={pack.recommended_opening_gbp}
          highlight
          editable={editable}
          onSave={async (v) => {
            await api.patchPack(pack.id, { recommended_opening_gbp: v });
            await onChanged();
          }}
        />
        <NumberCell
          label="Settlement low"
          value={pack.recommended_settlement_low_gbp}
          editable={editable}
          onSave={async (v) => {
            await api.patchPack(pack.id, { recommended_settlement_low_gbp: v });
            await onChanged();
          }}
        />
        <NumberCell
          label="Settlement high"
          value={pack.recommended_settlement_high_gbp}
          editable={editable}
          onSave={async (v) => {
            await api.patchPack(pack.id, { recommended_settlement_high_gbp: v });
            await onChanged();
          }}
        />
      </div>
      {pack.status === "settled" && pack.settled_rent_gbp != null && pack.current_rent_gbp != null && (
        <div className="mt-4 rounded-md bg-emerald-50 p-3 text-sm">
          <span className="font-medium text-emerald-900">
            Settled at £{pack.settled_rent_gbp.toLocaleString()}
          </span>
          <span className="ml-2 text-emerald-700">
            — uplift of £{(pack.settled_rent_gbp - pack.current_rent_gbp).toLocaleString()} (
            {(((pack.settled_rent_gbp - pack.current_rent_gbp) / pack.current_rent_gbp) * 100).toFixed(1)}%)
          </span>
        </div>
      )}
      <div className="mt-5 flex flex-wrap gap-2">
        <MarkSentButton pack={pack} onChanged={onChanged} />
        <SettleButton pack={pack} onChanged={onChanged} />
      </div>
    </div>
  );
}

function NumberCell({
  label,
  value,
  editable = false,
  highlight = false,
  onSave,
}: {
  label: string;
  value: number | null;
  editable?: boolean;
  highlight?: boolean;
  onSave?: (v: number) => Promise<void>;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<string>(value != null ? String(value) : "");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    setDraft(value != null ? String(value) : "");
  }, [value]);

  async function save() {
    const num = parseFloat(draft.replace(/[,£\s]/g, ""));
    if (!Number.isFinite(num) || num < 0) {
      setEditing(false);
      setDraft(value != null ? String(value) : "");
      return;
    }
    if (num === value) {
      setEditing(false);
      return;
    }
    setBusy(true);
    try {
      await onSave?.(num);
      setEditing(false);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="group">
      <div className="flex items-center gap-1 text-xs uppercase tracking-wide text-neutral-500">
        {label}
        {editable && !editing && (
          <Pencil size={10} className="opacity-0 group-hover:opacity-60 transition-opacity" />
        )}
      </div>
      {editing ? (
        <div className="mt-1 flex items-center gap-1">
          <span className="text-neutral-400">£</span>
          <input
            autoFocus
            inputMode="decimal"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") void save();
              if (e.key === "Escape") {
                setEditing(false);
                setDraft(value != null ? String(value) : "");
              }
            }}
            onBlur={save}
            disabled={busy}
            className="w-full rounded border border-neutral-300 px-1.5 py-0.5 text-lg font-medium tabular-nums focus:border-neutral-500 focus:outline-none"
          />
        </div>
      ) : (
        <button
          type="button"
          disabled={!editable}
          onClick={() => editable && setEditing(true)}
          className={`mt-1 block w-full text-left tabular-nums ${
            highlight ? "text-2xl font-semibold text-neutral-900" : "text-xl font-medium text-neutral-900"
          } ${editable ? "hover:bg-neutral-50 rounded px-1 -mx-1" : ""}`}
          title={editable ? "Click to edit" : ""}
        >
          {value == null ? "—" : `£${value.toLocaleString()}`}
        </button>
      )}
    </div>
  );
}

function MarkSentButton({ pack, onChanged }: { pack: PackDetail; onChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  if (pack.status === "settled") return null;
  return (
    <button
      disabled={busy || pack.status === "sent"}
      onClick={async () => {
        setBusy(true);
        try {
          await api.markPackSent(pack.id);
          await onChanged();
        } finally {
          setBusy(false);
        }
      }}
      className="rounded-md border border-neutral-300 bg-white px-3 py-1.5 text-sm hover:bg-neutral-50 disabled:opacity-50"
    >
      {pack.status === "sent" ? <><Check size={12} className="inline -mt-0.5 mr-1" /> Marked as sent</> : "Mark as sent"}
    </button>
  );
}

function SettleButton({ pack, onChanged }: { pack: PackDetail; onChanged: () => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [value, setValue] = useState<string>(
    pack.recommended_settlement_low_gbp ? String(pack.recommended_settlement_low_gbp) : ""
  );

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    const num = parseFloat(value.replace(/[,£\s]/g, ""));
    if (!Number.isFinite(num) || num <= 0) {
      setError("Enter a positive number, e.g. 53500");
      return;
    }
    setError(null);
    setBusy(true);
    try {
      await api.settlePack(pack.id, num);
      await onChanged();
      setOpen(false);
    } catch (err) {
      setError(String(err));
    } finally {
      setBusy(false);
    }
  }

  const uplift = (() => {
    const num = parseFloat(value.replace(/[,£\s]/g, ""));
    if (!Number.isFinite(num) || !pack.current_rent_gbp) return null;
    const diff = num - pack.current_rent_gbp;
    const pct = (diff / pack.current_rent_gbp) * 100;
    return { diff, pct };
  })();

  return (
    <>
      <button
        disabled={pack.status === "settled"}
        onClick={() => setOpen(true)}
        className="rounded-md bg-emerald-600 px-3 py-1.5 text-sm text-white hover:bg-emerald-700 disabled:opacity-50"
      >
        {pack.status === "settled" ? "Settled" : "Record settlement"}
      </button>
      {open && (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"
          onClick={(e) => { if (e.target === e.currentTarget) setOpen(false); }}
        >
          <form onSubmit={submit} className="w-full max-w-md rounded-lg bg-white p-5 shadow-xl">
            <h2 className="text-base font-semibold">Record settled rent</h2>
            <p className="mt-1 text-sm text-neutral-500">
              Locks the pack as settled and adds the deal as an internal comparable for future reviews.
            </p>
            <label className="mt-4 block text-sm">
              <span className="text-neutral-700">Settled rent (£/year)</span>
              <div className="mt-1 flex rounded-md border border-neutral-300 focus-within:border-neutral-500 focus-within:ring-1 focus-within:ring-neutral-500">
                <span className="flex items-center px-3 text-neutral-400">£</span>
                <input
                  autoFocus
                  inputMode="decimal"
                  value={value}
                  onChange={(e) => setValue(e.target.value)}
                  placeholder="53,500"
                  className="flex-1 rounded-r-md bg-transparent py-2 pr-3 text-sm focus:outline-none"
                />
              </div>
            </label>
            {pack.recommended_settlement_low_gbp && pack.recommended_settlement_high_gbp && (
              <div className="mt-2 text-xs text-neutral-500">
                Recommended range: £{pack.recommended_settlement_low_gbp.toLocaleString()} – £{pack.recommended_settlement_high_gbp.toLocaleString()}
              </div>
            )}
            {uplift && (
              <div className={`mt-2 text-sm font-medium ${uplift.diff >= 0 ? "text-emerald-700" : "text-red-700"}`}>
                {uplift.diff >= 0 ? "Uplift" : "Decrease"}: £{Math.abs(uplift.diff).toLocaleString()} ({uplift.pct.toFixed(1)}%)
              </div>
            )}
            {error && <div className="mt-2 rounded border border-red-200 bg-red-50 p-2 text-xs text-red-800">{error}</div>}
            <div className="mt-5 flex justify-end gap-2">
              <button type="button" onClick={() => setOpen(false)} className="rounded-md border border-neutral-300 bg-white px-3 py-1.5 text-sm hover:bg-neutral-50" disabled={busy}>
                Cancel
              </button>
              <button type="submit" disabled={busy || !value.trim()} className="rounded-md bg-emerald-600 px-3 py-1.5 text-sm text-white hover:bg-emerald-700 disabled:opacity-50">
                {busy ? "Saving…" : "Record settlement"}
              </button>
            </div>
          </form>
        </div>
      )}
    </>
  );
}

// ---- Word-style document view ------------------------------------------

function DocumentView({ packId, doc }: { packId: string; doc: PackDocumentOut }) {
  return (
    <div className="rounded-lg border border-neutral-200 bg-neutral-100 overflow-hidden">
      <div className="flex items-center justify-between border-b border-neutral-200 bg-white px-4 py-2.5">
        <div className="text-sm font-medium">{KIND_LABEL[doc.kind] ?? doc.kind}</div>
        <a
          href={api.packDocumentUrl(packId, doc.id)}
          className="rounded-md bg-neutral-900 px-3 py-1.5 text-xs text-white hover:bg-neutral-700"
          download={doc.filename}
        >
          Download .docx
        </a>
      </div>

      {/* Paper card */}
      <div className="px-6 py-8 sm:px-12">
        <div
          className="mx-auto max-w-[720px] rounded-sm bg-white shadow-md ring-1 ring-neutral-200"
          style={{
            // A4 portrait-ish margins (in CSS px). Real A4 width = 793px @ 96dpi.
            paddingTop: "60px",
            paddingBottom: "60px",
            paddingLeft: "72px",
            paddingRight: "72px",
            fontFamily: 'Georgia, "Source Serif Pro", "Source Serif 4", Cambria, "Times New Roman", serif',
            color: "#1a1a1a",
          }}
        >
          {doc.markdown_content ? (
            <Markdown text={doc.markdown_content} />
          ) : (
            <div className="text-neutral-500 text-sm italic">No preview available.</div>
          )}
        </div>
      </div>
    </div>
  );
}

// ---- Markdown renderer (Word-styled) -----------------------------------

function Markdown({ text }: { text: string }) {
  const blocks = parseBlocks(text);
  return (
    <div style={{ lineHeight: 1.55, fontSize: "11pt" }}>
      {blocks.map((b, i) => {
        if (b.type === "heading") {
          if (b.level === 1) {
            return (
              <h1 key={i} style={{ fontSize: "20pt", fontWeight: 600, marginTop: i === 0 ? 0 : "1.4em", marginBottom: "0.6em", lineHeight: 1.25 }}>
                {renderInline(b.text)}
              </h1>
            );
          }
          if (b.level === 2) {
            return (
              <h2 key={i} style={{ fontSize: "14pt", fontWeight: 600, marginTop: "1.4em", marginBottom: "0.5em", lineHeight: 1.3, color: "#0f172a" }}>
                {renderInline(b.text)}
              </h2>
            );
          }
          return (
            <h3 key={i} style={{ fontSize: "12pt", fontWeight: 600, marginTop: "1.1em", marginBottom: "0.4em", lineHeight: 1.3, color: "#0f172a" }}>
              {renderInline(b.text)}
            </h3>
          );
        }
        if (b.type === "bullets") {
          return (
            <ul key={i} style={{ marginLeft: "1.4em", marginTop: "0.4em", marginBottom: "0.6em", listStyleType: "disc" }}>
              {b.items.map((item, j) => (
                <li key={j} style={{ marginBottom: "0.25em" }}>{renderInline(item)}</li>
              ))}
            </ul>
          );
        }
        if (b.type === "numbered") {
          return (
            <ol key={i} style={{ marginLeft: "1.4em", marginTop: "0.4em", marginBottom: "0.6em", listStyleType: "decimal" }}>
              {b.items.map((item, j) => (
                <li key={j} style={{ marginBottom: "0.25em" }}>{renderInline(item)}</li>
              ))}
            </ol>
          );
        }
        if (b.type === "table") {
          return (
            <table key={i} style={{ width: "100%", borderCollapse: "collapse", marginTop: "0.6em", marginBottom: "0.6em", fontSize: "10pt" }}>
              <thead>
                <tr>
                  {b.header.map((h, j) => (
                    <th key={j} style={{ borderBottom: "2px solid #1e293b", padding: "6px 8px", textAlign: "left", fontWeight: 600 }}>
                      {renderInline(h)}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {b.rows.map((row, ri) => (
                  <tr key={ri}>
                    {row.map((c, ci) => (
                      <td key={ci} style={{ borderBottom: "1px solid #e2e8f0", padding: "6px 8px", verticalAlign: "top" }}>
                        {renderInline(c)}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          );
        }
        if (b.type === "rule") {
          return <hr key={i} style={{ border: 0, borderTop: "1px solid #e2e8f0", margin: "1.2em 0" }} />;
        }
        return (
          <p key={i} style={{ margin: "0.5em 0", textAlign: "justify" }}>
            {renderInline(b.text)}
          </p>
        );
      })}
    </div>
  );
}

type Block =
  | { type: "heading"; level: 1 | 2 | 3; text: string }
  | { type: "paragraph"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "numbered"; items: string[] }
  | { type: "table"; header: string[]; rows: string[][] }
  | { type: "rule" };

function parseBlocks(md: string): Block[] {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const blocks: Block[] = [];
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) { i++; continue; }

    if (/^---+$/.test(line.trim())) { blocks.push({ type: "rule" }); i++; continue; }

    if (line.startsWith("### ")) { blocks.push({ type: "heading", level: 3, text: line.slice(4) }); i++; continue; }
    if (line.startsWith("## "))  { blocks.push({ type: "heading", level: 2, text: line.slice(3) }); i++; continue; }
    if (line.startsWith("# "))   { blocks.push({ type: "heading", level: 1, text: line.slice(2) }); i++; continue; }

    if (line.trimStart().startsWith("|") && i + 1 < lines.length && lines[i + 1].includes("---")) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trimStart().startsWith("|")) { tableLines.push(lines[i]); i++; }
      const cells = (l: string) => l.trim().replace(/^\||\|$/g, "").split("|").map((c) => c.trim());
      const header = cells(tableLines[0]);
      const rows = tableLines.slice(2).map(cells);
      blocks.push({ type: "table", header, rows });
      continue;
    }

    if (/^[-*] /.test(line.trimStart())) {
      const items: string[] = [];
      while (i < lines.length && /^[-*] /.test(lines[i].trimStart())) {
        items.push(lines[i].trimStart().replace(/^[-*] /, ""));
        i++;
      }
      blocks.push({ type: "bullets", items });
      continue;
    }

    if (/^\d+\.\s/.test(line.trimStart())) {
      const items: string[] = [];
      while (i < lines.length && /^\d+\.\s/.test(lines[i].trimStart())) {
        items.push(lines[i].trimStart().replace(/^\d+\.\s/, ""));
        i++;
      }
      blocks.push({ type: "numbered", items });
      continue;
    }

    const paraLines = [line];
    i++;
    while (i < lines.length && lines[i].trim() && !/^([#\-*|]|\d+\.\s|---+$)/.test(lines[i].trimStart())) {
      paraLines.push(lines[i]);
      i++;
    }
    blocks.push({ type: "paragraph", text: paraLines.join(" ") });
  }
  return blocks;
}

function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith("**") && p.endsWith("**")
          ? <strong key={i}>{p.slice(2, -2)}</strong>
          : <span key={i}>{p}</span>
      )}
    </>
  );
}

// ---- Comparables drawer -------------------------------------------------

function ComparablesDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [items, setItems] = useState<Comparable[] | null>(null);

  useEffect(() => {
    if (!open) return;
    api.listComparables().then(setItems).catch(() => setItems([]));
  }, [open]);

  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) { if (e.key === "Escape") onClose(); }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-40 flex justify-end bg-black/30" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <aside role="dialog" aria-labelledby="comps-drawer-title" className="h-full w-full max-w-md overflow-y-auto bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-neutral-100 px-5 py-4">
          <h2 id="comps-drawer-title" className="text-base font-semibold">Comparables in evidence set</h2>
          <button onClick={onClose} aria-label="Close" className="rounded p-1 text-neutral-500 hover:bg-neutral-100 hover:text-neutral-800">
            <X size={18} />
          </button>
        </div>

        <div className="px-5 py-4">
          {items === null ? (
            <div className="text-sm text-neutral-500">Loading…</div>
          ) : items.length === 0 ? (
            <div className="text-sm text-neutral-500">No comparables in the workspace yet.</div>
          ) : (
            <ul className="space-y-2">
              {items.map((c) => {
                const psf = c.area_sqft && c.area_sqft > 0 ? c.rent_pa_gbp / c.area_sqft : null;
                return (
                  <li key={c.id} className="rounded-md border border-neutral-200 p-3">
                    <div className="font-medium text-sm text-neutral-900">{c.address}</div>
                    <div className="mt-1 text-xs text-neutral-600 tabular-nums">
                      £{c.rent_pa_gbp.toLocaleString()}/yr
                      {c.area_sqft && ` · ${c.area_sqft.toLocaleString()} sq ft`}
                      {psf != null && ` · £${psf.toFixed(0)}/sq ft`}
                    </div>
                    <div className="mt-1 text-xs text-neutral-500">
                      {c.use_class && <span>{c.use_class} · </span>}
                      {c.deal_date && <span>{format(parseISO(c.deal_date), "d MMM yyyy")} · </span>}
                      <span>{c.source}</span>
                    </div>
                    {c.notes && <div className="mt-1 text-xs text-neutral-500 italic">{c.notes}</div>}
                  </li>
                );
              })}
            </ul>
          )}
          <Link
            href="/comparables"
            onClick={onClose}
            className="mt-4 inline-flex items-center gap-1.5 text-sm text-blue-700 hover:underline"
          >
            Manage comparables <ExternalLink size={12} />
          </Link>
        </div>
      </aside>
    </div>
  );
}
