"""dev DB drift cleanup — bring local SQLite in line with the model.

The early dev DB had columns added via raw `ALTER TABLE` from
`scripts/migrate_documents.py` and `scripts/backfill_properties.py`
without DEFAULTs / NOT NULL constraints. The model defines them as
NOT NULL with sensible server_defaults. This migration tightens the
live DB to match. Idempotent and safe on fresh DBs created from baseline.

Revision ID: 640471149aad
Revises: 87eab28c8bf2
Create Date: 2026-05-03 21:20:54.843186
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640471149aad'
down_revision: Union[str, Sequence[str], None] = '87eab28c8bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('summary_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('summary_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               nullable=False)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('address_normalised',
               existing_type=sa.VARCHAR(length=512),
               server_default=None,
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
        batch_op.alter_column('address_normalised',
               existing_type=sa.VARCHAR(length=512),
               server_default=sa.text('("")'),
               nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('summary_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'skipped'"),
               nullable=True)
        batch_op.alter_column('summary_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
