"""baseline schema

Revision ID: 87eab28c8bf2
Revises: 
Create Date: 2026-05-03 21:19:29.535709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eab28c8bf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('address_normalised', sa.String(length=512), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('landlord_client', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_address_normalised'), ['address_normalised'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_landlord_client'), ['landlord_client'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('record_json', sa.JSON(), nullable=True),
    sa.Column('extraction_model', sa.String(length=64), nullable=True),
    sa.Column('extraction_seconds', sa.Float(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leases_status'), ['status'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('account_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('slack_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('channel_label', sa.String(length=255), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('comparables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('rent_pa_gbp', sa.Float(), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('frontage_m', sa.Float(), nullable=True),
    sa.Column('use_class', sa.String(length=32), nullable=True),
    sa.Column('deal_date', sa.DateTime(), nullable=True),
    sa.Column('deal_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('derived_from_lease_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparables_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparables_deal_date'), ['deal_date'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=True),
    sa.Column('summary_seconds', sa.Float(), nullable=True),
    sa.Column('summary_status', sa.String(length=32), nullable=False),
    sa.Column('summary_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_lease_id'), ['lease_id'], unique=False)

    op.create_table('field_edits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_edits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_edits_lease_id'), ['lease_id'], unique=False)

    op.create_table('lease_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=64), nullable=True),
    sa.Column('pushed_to_google', sa.Boolean(), nullable=False),
    sa.Column('pushed_to_outlook', sa.Boolean(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('outlook_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lease_events_lease_id'), ['lease_id'], unique=False)

    op.create_table('rent_review_packs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('lease_event_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_rent_gbp', sa.Float(), nullable=True),
    sa.Column('recommended_opening_gbp', sa.Float(), nullable=True),
    sa.Column('recommended_settlement_low_gbp', sa.Float(), nullable=True),
    sa.Column('recommended_settlement_high_gbp', sa.Float(), nullable=True),
    sa.Column('settled_rent_gbp', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('generator_model', sa.String(length=64), nullable=True),
    sa.Column('generated_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('comparables_used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_event_id'], ['lease_events.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_review_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_review_packs_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rent_review_packs_status'), ['status'], unique=False)

    op.create_table('pack_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pack_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['rent_review_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pack_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pack_documents_pack_id'), ['pack_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pack_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pack_documents_pack_id'))

    op.drop_table('pack_documents')
    with op.batch_alter_table('rent_review_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_review_packs_status'))
        batch_op.drop_index(batch_op.f('ix_rent_review_packs_lease_id'))

    op.drop_table('rent_review_packs')
    with op.batch_alter_table('lease_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_events_lease_id'))
        batch_op.drop_index(batch_op.f('ix_lease_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_lease_events_event_date'))

    op.drop_table('lease_events')
    with op.batch_alter_table('field_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_edits_lease_id'))

    op.drop_table('field_edits')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_lease_id'))

    op.drop_table('documents')
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparables_deal_date'))
        batch_op.drop_index(batch_op.f('ix_comparables_address'))

    op.drop_table('comparables')
    with op.batch_alter_table('slack_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_integrations_user_id'))

    op.drop_table('slack_integrations')
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_user_id'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leases_status'))
        batch_op.drop_index(batch_op.f('ix_leases_property_id'))
        batch_op.drop_index(batch_op.f('ix_leases_created_at'))

    op.drop_table('leases')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_landlord_client'))
        batch_op.drop_index(batch_op.f('ix_properties_address_normalised'))

    op.drop_table('properties')
    # ### end Alembic commands ###
