#!/usr/bin/env bash
# Thin wrapper around alembic for local dev.
#
#   scripts/db.sh upgrade            # apply pending migrations
#   scripts/db.sh current            # show current revision
#   scripts/db.sh history            # show revision graph
#   scripts/db.sh new "what changed" # create a new autogenerated revision
#   scripts/db.sh check              # warn if model and DB have drifted
#
# All commands run inside the project's virtualenv if one exists at .venv/.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ALEMBIC="alembic"
if [ -x ".venv/bin/alembic" ]; then
  ALEMBIC=".venv/bin/alembic"
fi

cmd="${1:-help}"
shift || true

case "$cmd" in
  upgrade)  exec "$ALEMBIC" upgrade head ;;
  current)  exec "$ALEMBIC" current ;;
  history)  exec "$ALEMBIC" history ;;
  check)    exec "$ALEMBIC" check ;;
  new)
    if [ -z "${1:-}" ]; then
      echo "usage: scripts/db.sh new \"short description\"" >&2
      exit 2
    fi
    exec "$ALEMBIC" revision --autogenerate -m "$1"
    ;;
  *)
    cat <<EOF
LeaseOS DB / migrations helper.
Usage:
  scripts/db.sh upgrade       Apply pending migrations to \$DATABASE_URL
  scripts/db.sh current       Show current revision
  scripts/db.sh history       Show revision graph
  scripts/db.sh new "msg"     Autogenerate a new revision against the model
  scripts/db.sh check         Detect drift between model and DB
EOF
    exit 1
    ;;
esac
